version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: timeblocker
      POSTGRES_PASSWORD: timeblocker_password
      POSTGRES_DB: timeblocker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - timeblocker-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://timeblocker:timeblocker_password@postgres:5432/timeblocker
      NODE_ENV: production
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/app/src
      - ./backend/migrations:/app/migrations
    networks:
      - timeblocker-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production
      VITE_API_URL: http://backend:3000
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    networks:
      - timeblocker-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - timeblocker-network

volumes:
  postgres_data:

networks:
  timeblocker-network:
    driver: bridge